### ISSUE TITLE
Debug: internal, implementation, error     Error: handler method did not return a value, a promise, or throw an error

### ISSUE THREAD

**Issue by shushantkumar** [hapijs/hapijs.com#571] opened 2018-03-11 05:58 UTC
Hi,
I'm using hapi version ^17.2.1 and I have a problem because I get an error in route handler:
Debug: internal, implementation, error
    Error: handler method did not return a value, a promise, or throw an error

I am using MySQL database. So when I'm sending a query to the database and getting the result from the database. Using console.log, it is getting printed in the console but since I'm returning the result there itself within the query as a response it is not returning anything from the main handler function(case-1). Storing the result from the database in a new variable outside scope of query function and returning it as a response outside query function doesn't help either (case-2), it just returns a blank response.

case-1
`server.route(

    {

    method:'GET',

    path:'/productget',

    config:{
        handler: (request, h) =>{           
            var sql = "select * from product_details";
            con.query(sql,function (err, result) {
                if (err) throw err;    
               console.log(result);
               return h.response(result); 
            }); 
        },
        validate: {
            failAction: Relish.failAction,
        }   
    }
});`

case-2
`server.route(

    {

    method:'GET',

    path:'/productget',
    config:{
        let temp;
        handler: (request, h) =>{           
            var sql = "select * from product_details";
            con.query(sql,this,function (err, result) {
                if (err) throw err;    
               console.log(result);
               this.temp=result;
            }); 
          return h.response(temp); 
        },
        validate: {
            failAction: Relish.failAction,
        }   
    }
});`

Can someone help me out in this how can I return a response from server within the query function or using any other method?

**Comment by Marsup** [comment] 2018-03-11 08:52
Duplicate of https://github.com/hapijs/discuss/issues/643.

**Closed by Marsup** 2018-03-11 08:52 UTC
Labels: non-issue
