### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by traysonkelii** [hapijs/hapijs.com#591] opened 2018-06-11 17:38 UTC
The site is down again
<img width="1136" alt="screen shot 2018-06-11 at 11 37 59 am" src="https://user-images.githubusercontent.com/25124556/41247695-00357de8-6d6c-11e8-8a10-36069c7da750.png">

**Comment by JustinBeaudry** [comment] 2018-06-11 17:41
Dupe of #590

**Closed** 2018-06-11 18:20 UTC
